// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("gtmetrix-net")]
[assembly: AssemblyProductAttribute("gtmetrix-net")]
[assembly: AssemblyDescriptionAttribute("GTmetrix-net .Net client")]
[assembly: AssemblyVersionAttribute("0.0.1.7")]
[assembly: AssemblyFileVersionAttribute("0.0.1.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1.7";
        internal const string InformationalVersion = "0.0.1.7";
    }
}
